/// Flutter icons TiktokIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TiktokIcon
///      fonts:
///       - asset: fonts/TiktokIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TiktokIcon {
  TiktokIcon._();

  static const _kFontFam = 'TiktokIcon';
  static const String _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData me = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draft = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liked = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
